@startuml
actor Staff
activate Staff

participant UpdateGardenTimesheetScreen
Staff -> UpdateGardenTimesheetScreen: access
activate UpdateGardenTimesheetScreen
UpdateGardenTimesheetScreen -> UpdateGardenTimesheetScreen: click update a garden timesheet

participant GardenTimesheetController
UpdateGardenTimesheetScreen -> GardenTimesheetController: update(updateGardenTimesheetDto)
activate GardenTimesheetController
GardenTimesheetController -> GardenTimesheetController: validate if garden timeshet has any classes scheduled

alt garden timeshet has any classes scheduled
    GardenTimesheetController --> UpdateGardenTimesheetScreen: show error message
end

participant IGardenTimesheetService
GardenTimesheetController -> IGardenTimesheetService: update(id, status)
activate IGardenTimesheetService

participant IGardenTimesheetRepository
IGardenTimesheetService -> IGardenTimesheetRepository: findOneAndUpdate(id, status)
activate IGardenTimesheetRepository

participant INotificationService
database Database
IGardenTimesheetRepository -> Database: execute(payload)
activate Database
Database --> IGardenTimesheetRepository: return data
deactivate Database

IGardenTimesheetRepository --> IGardenTimesheetService: return data
deactivate IGardenTimesheetRepository

IGardenTimesheetService -> INotificationService: send notification to garden manager
activate INotificationService

INotificationService --> IGardenTimesheetService: return data
deactivate INotificationService

IGardenTimesheetService --> GardenTimesheetController: return data
deactivate IGardenTimesheetService

GardenTimesheetController --> UpdateGardenTimesheetScreen: show success message
deactivate GardenTimesheetController
@enduml