export const COURSE_LIST_PROJECTION = [
  '_id',
  'code',
  'title',
  'price',
  'level',
  'type',
  'thumbnail',
  'status',
  'learnerLimit',
  'rate',
  'discount',
  'instructorId',
  'isPublished',
  'createdAt',
  'updatedAt'
] as const

export const COURSE_DETAIL_PROJECTION = [
  '_id',
  'code',
  'title',
  'description',
  'price',
  'level',
  'type',
  'thumbnail',
  'media',
  'status',
  'lessons',
  'assignments',
  'learnerLimit',
  'rate',
  'discount',
  'gardenRequiredToolkits',
  'instructorId',
  'isPublished',
  'createdAt',
  'updatedAt'
] as const

export const PUBLIC_COURSE_DETAIL_PROJECTION = [
  '_id',
  'code',
  'title',
  'description',
  'price',
  'level',
  'type',
  'thumbnail',
  'media',
  'status',
  'lessons._id',
  'lessons.title',
  'assignments._id',
  'assignments.title',
  'learnerLimit',
  'rate',
  'discount',
  'gardenRequiredToolkits',
  'instructorId',
  'isPublished',
  'createdAt',
  'updatedAt'
] as const
